### PR TITLE
fix: Resolve Posthog console warning

### LINKED ISSUE #481: `posthog` was already loaded elsewhere. This may cause issues.
**Describe the bug**
The console reads a warning:

```
[PostHog.js] `posthog` was already loaded elsewhere. This may cause issues.
```

**To Reproduce**
1. Run the app
2. Open the browser console
3. View the warning

**Expected behavior**
Posthog is only loaded once. No warning is shown.

**Screenshots**

Image

**Desktop (please complete the following information):**
 - OS: macOS Sequoia 15.3
 - Browser: Chrome

### PR DESCRIPTION
**Pull request by Ibrahimsuf**
## What changed?

Use web js to load posthog instead of `PostHogProvider`

#481 
## Why?

Posthog has a [bug](https://github.com/PostHog/posthog-js/issues/723) that causes it to load itself twice when using `PostHogProvider`.  The recommended fix was to use the web js loading instead of the `PostHogProvider`.

### CODE REVIEW

File: src/main.tsx [hunk 1]
```diff
@@ -96,33 +99,18 @@ const InnerApp = () => {
...
 };
 
-const postHogOptions: Partial<PostHogConfig> = {
-  api_host: import.meta.env.VITE_REACT_APP_PUBLIC_POSTHOG_HOST,
-  // Since we're using TanStack Router, we need to track pageviews manually
-  capture_pageview: false,
-  // Enable web vitals
-  capture_performance: {
-    web_vitals: true,
-  },
```
Comment (kydecker) [inline src/main.tsx]: We need to keep these settings in place!

File: src/main.tsx [hunk 2]
```diff
@@ -96,33 +99,18 @@ const InnerApp = () => {
...
-};
-
 const rootElement = document.getElementById("root")!;
 if (!rootElement.innerHTML) {
   const root = createRoot(rootElement);
   root.render(
     <StrictMode>
       <HelmetProvider>
         <ConvexAuthProvider client={convex}>
-          <PostHogProvider
```
Comment (kydecker) [inline src/main.tsx:116]: In the issue you linked there's [a comment](https://github.com/PostHog/posthog-js/issues/723#issuecomment-2636594375) that moving the provider up in the hierarchy can resolve it — can you try doing that here and see if it fixes it?

File: src/routes/_unauthenticated/signin.tsx [hunk 3]
```diff
@@ -248,6 +248,7 @@ const ForgotPassword = ({
             setDidSendCode(true);
           })
           .catch((error) => {
+            console.log("Got to this step");
```
Comment (kydecker) [inline src/routes/_unauthenticated/signin.tsx]: Remove this before merge :)

File: src/main.tsx [hunk 4]
```diff
@@ -14,13 +14,16 @@ import {
 import { ArrowLeft, TriangleAlert } from "lucide-react";
 import { LazyMotion, domAnimation } from "motion/react";
 import { ThemeProvider } from "next-themes";
-import type { PostHogConfig } from "posthog-js";
-import { PostHogProvider } from "posthog-js/react";
+import posthog from "posthog-js";
```
Comment (kydecker) [inline src/main.tsx]: In several other files we're currently using `import posthog from "posthog-js"`, but I think we should be using the hook `import { usePostHog } from "posthog-js/react"` instead?

File: .changeset/breezy-moose-remain.md [hunk 5]
```diff
@@ -0,0 +1,5 @@
+---
+"namesake": patch
+---
+
+fix: posthog was already loaded elsewhere
```
Comment (kydecker) [inline .changeset/breezy-moose-remain.md]:
```suggestion
Fix console warning about Posthog loading more than once
```
nit

**Review by kydecker — COMMENTED** [review]
Hey @Ibrahimsuf, thanks for submitting this!

Appreciate the link to the issue filed with Posthog. Left a few comments for other things to try.

File: src/main.tsx (hunk 2 above)
Comment (Ibrahimsuf) [reply src/main.tsx:116]: You are correct if we move `PostHogProvider` to to the top it fixes the warning.

File: src/main.tsx (hunk 4 above)
Comment (Ibrahimsuf) [reply src/main.tsx]: It seems like we can use `PostHogProvider` as long as it is high enough in the hierarchy.

File: src/main.tsx (hunk 2 above)
Comment (Ibrahimsuf) [reply src/main.tsx:116]: I don't know what exactly it needs to be ahead of, but it only works at the top of the `root.render` block.

File: src/main.tsx (hunk 4 above)
Comment (kydecker) [reply src/main.tsx]: Right, I mean anywhere else in the application that currently has `import posthog from "posthog-js"` needs to be replaced with a hook.

[From the docs:](https://posthog.com/docs/libraries/react#using-posthog-js-functions)

> Do not directly import posthog apart from installation as shown above. This will likely cause errors as the library might not be initialized yet. Initialization is handled automatically when you use the PostHogProvider and hook.

File: src/main.tsx (hunk 2 above)
Comment (kydecker) [reply src/main.tsx:116]: We still need to keep it inside of `StrictMode`. Try relocating it there and replacing other posthog imports with the `usePosthog` hook.

If that doesn't fix it, we may also need to [initialize the client instance](https://posthog.com/docs/libraries/react#posthog-provider) instead of passing in `apiKey` and `options`.

**Comment by kydecker** [comment]
@Ibrahimsuf I took the time to get the rest of this PR over the finish line! Thank you for your contribution!

**Review by kydecker — APPROVED** [review]
