### PR TITLE
fix: Improve toast placement

### LINKED ISSUE #601: Toast placement could be improved
On mobile the toast location covers the navigation, and should be adjusted to clear the navbar.

https://github.com/user-attachments/assets/04ae8435-3554-460f-9021-c6e721020bc4

On desktop the toast location covers the sidebar navigation, and should be moved to the right side of the viewport.

https://github.com/user-attachments/assets/9459a2a0-17ee-4e35-a1af-dbe4da75d898

### PR DESCRIPTION
**Pull request by OmarRdz12**
## What changed?
Modified `Toaster` properties to change the position of toasts to improve navigation.

https://github.com/user-attachments/assets/123e9916-086b-4c8b-8b76-bd7d52321179

https://github.com/user-attachments/assets/bd3dd6bb-237e-4db2-9634-37f04202cfb0

Fixes #601 

## Why?
Whenever the `toast` was displayed to provide feedback to the user, it was placed above the bottom navigation bar, making it impossible to use until the notification disappeared.

## How was this change made?
- Updated `Toaster` on `_root.tsx` to manage `position` property as bottom-right and `mobileOffset` as bottom: '60px'.

## How was this tested?
Manual.

## Anything else?
No.

### CODE REVIEW

File: src/routes/__root.tsx [hunk 1]
```diff
@@ -74,8 +74,9 @@ function RootRoute() {
       <Toaster
         theme={theme as "light" | "dark" | "system"}
         offset={16}
+        mobileOffset={{ bottom: "60px" }}
```
Comment (kydecker) [inline src/routes/__root.tsx]:
```suggestion
        mobileOffset={{ bottom: "68px" }}
```
A little bit of extra space so the margins are the same!

**Review by kydecker — COMMENTED** [review]
Great, easy! One small tweak to sizing and should be good to go. :)

**Comment by kydecker** [comment]
You can ignore the failing Storybook test! There's a permissions issue I need to fix.

**Review by kydecker — APPROVED** [review]

**Comment by kydecker** [comment]
Thanks so much for your first contribution, @OmarRdz12! Myself and the rest of the Namesake team really appreciate it 🙏
