### PR TITLE
fix: Add error boundaries and PostHog reporting

### LINKED ISSUE #116: Improve error boundaries and error handling
- [x] Use `ErrorBoundary`, `Suspense`, etc. to prevent the app from breaking when something doesn't render correctly.
- [x] Test by forcing different parts of the app into an error state and ensuring that most of the app still renders.
- [x] Exceptions should be reported to PostHog

### PR DESCRIPTION
**Pull request by kydecker**
## What changed?
Fixes #116. Add error boundaries around `AppSidebar` and `AppContent` and report any errors to PostHog.

## Why?
Prevent the entire app from crashing if something goes wrong. Display a more appealing looking error.

## How was this change made?
Added `PostHogErrorBoundary` to the two primary components used within the app.

## How was this tested?
Wrote new tests, inserted a dummy component which errors in order to force state.

### CODE REVIEW

File: src/components/app/AppContent/AppContent.tsx [hunk 1]
```diff
@@ -9,5 +12,20 @@ export const AppContent = ({ children, className }: AppContentProps) => {
   const styles = tv({
     base: "flex-1 w-full max-w-[960px] mx-auto",
   });
-  return <main className={styles({ className })}>{children}</main>;
+
+  const fallback = () => {
+    return (
+      <Empty
+        title="Something went wrong"
+        subtitle="We've been notified of the issue. Refresh the page to try again."
```
Comment (mbbischoff) [inline src/components/app/AppContent/AppContent.tsx:20]: is this one also smart quoted magically?

File: src/components/common/Empty/Empty.tsx [hunk 2]
```diff
@@ -36,10 +36,12 @@ export function Empty({
         className,
       )}
     >
-      <Icon size={40} className="text-gray-8 shrink-0 stroke-[1.5px]" />
+      <Icon size={40} className="text-gray-9 shrink-0 stroke-2" />
       <Heading className="font-semibold text-xl">{smartquotes(title)}</Heading>
       {subtitle && (
-        <p className="text-gray-dim -mt-4">{smartquotes(subtitle)}</p>
+        <p className="text-gray-dim -mt-3 text-center">
+          {smartquotes(subtitle)}
```
Comment (mbbischoff) [inline src/components/common/Empty/Empty.tsx:43]: Answer: yes

**Review by mbbischoff — COMMENTED** [review]
lgtm
