### PR TITLE
fix: Update language around fee waivers; display costs within form

### LINKED ISSUE #577: Fee waiver question on MA Court Order doesn't account for public assistance qualifiers
Fee waivers are possible *without* proof of income in certain circumstances.

Re: Court Order process question "Do you need to apply for a fee waiver?"; Add option "I receive public assistance under one of these five programs" (list of specific programs viewable here: https://www.mass.gov/doc/affidavit-of-indigency/download). This option would not require proof of income for Affidavit of Indigency.

### PR DESCRIPTION
**Pull request by kydecker**
## What changed?
The language for the fee waiver question incorrectly stated that it's required to provide proof of income. Some options for the fee waiver do not involve proof of income, so this removes that statement from the question and answer text. Resolves #577.

Additionally, creates a new `QuestCostsTable` component to reuse displaying costs for a quest, and inserts it within the form. Tweaks styling.

| Before | After |
|--------|--------|
| CleanShot 2025-05-30 at 16 06 06@2x | CleanShot 2025-05-30 at 16 05 58@2x |
| CleanShot 2025-05-30 at 16 08 27@2x | CleanShot 2025-05-30 at 16 08 13@2x | 

## Why?
Make it easier for people to understand costs and requirements.

## How was this change made?
- Extracted costs table into new `QuestCostsTable` component; changed markup from a description list to a proper `table`
- Inserted into the existing `Popover` for `QuestCostsBadge` and conditionally display within `ma-court-order` form when the fee waiver question is undefined or "No"

## How was this tested?
Added new unit tests.

## Anything else?
Changes the form route from `ma-court-order` to `court-order-ma` to match the quest naming scheme. Will require updating the link in production after merge.

### CODE REVIEW

File: src/components/quests/QuestCostsBadge/QuestCostsBadge.tsx [hunk 1]
```diff
@@ -187,30 +161,8 @@ export const QuestCostsBadge = ({
...
-                  </dd>
-                </Fragment>
-              ))}
-              <dt className="pr-4 border-t border-gray-a5 pt-2 mt-2">Total</dt>
-              <dd className="text-right border-t border-gray-a5 pt-2 mt-2">
-                {getTotalCosts(costs)}
-              </dd>
-            </dl>
+          <Popover placement="bottom" className="p-4">
+            <QuestCostsTable costs={costs} />
```
Comment (mbbischoff) [inline src/components/quests/QuestCostsBadge/QuestCostsBadge.tsx:165]: Dig this extraction

**Review by mbbischoff — APPROVED** [review]
Looks great
