### PR TITLE
fix: Show error when signing in with unregistered email

### LINKED ISSUE #167: Error message not shown on unsuccessful login
**Describe the bug**
Currently if a user fails to log in, the form is cleared and no message is displayed.

**To Reproduce**
1. Log in with incorrect credentials or nonexistent account
2. No message is displayed

**Expected behavior**
An error displays letting the user know the account doesn't exist or the password is wrong.

### LINKED ISSUE #296: Display an error message on sign in if the email does not belong to a registered user
If a user attempts to sign in using an email that doesn't exist in the database, display an error banner.

The banner should say:

> There isn't an account for this email. Would you like to [register a new account]?

"register a new account" should link to the registration tab.

### PR DESCRIPTION
**Pull request by nakul-py**
### What changed?
- Added a check to verify if the email exists before attempting the sign-in process.
- Display an error message if the email is not registered, prompting users to register a new account.
- If the email is not found, users are provided with a link to the registration tab for account creation.
- Fixes #296
### Why?

- This change was implemented to improve the user experience by notifying users immediately when they attempt to sign in with an unregistered email.
- Users no longer need to guess why they can't log in or be confused by no feedback, leading to better usability and fewer failed attempts.

## Screencast: 

https://github.com/user-attachments/assets/0354c7b0-7a4e-47c6-a60a-b697a66a3e88

### CODE REVIEW

File: src/routes/_unauthenticated/signin.tsx [hunk 1]
```diff
@@ -35,34 +35,78 @@ const SignIn = () => {
...
-        error instanceof ConvexError
-          ? setError(error.message)
-          : setError(error),
-      )
-      .then(() => navigate({ to: "/" }))
-      .finally(() => setIsSubmitting(false));
+      navigate({ to: "/" });
+    } catch (error) {
+      setError(
+        error instanceof Error ? error.message : "An unexpected error occurred."
```
Comment (kydecker) [inline src/routes/_unauthenticated/signin.tsx]: We'll want to keep this as `instanceof ConvexError`.

File: src/routes/_unauthenticated/signin.tsx [hunk 2]
```diff
@@ -35,34 +35,78 @@ const SignIn = () => {
...
+      headers: { 'Content-Type': 'application/json' },
+      body: JSON.stringify({ email }),
+    });
+  
+    if (!response.ok) {
+      return false;
+    }
+    const data = await response.json();
+    return data.exists;
+  };
```
Comment (kydecker) [inline src/routes/_unauthenticated/signin.tsx]: This API endpoint `check-user-exists` doesn't exist! Instead you'll need to set and fetch the error from the sign in flow. You can add a `ConvexError` to support returning whether the email exists or not: https://docs.convex.dev/functions/error-handling/application-errors

**Review by kydecker — CHANGES_REQUESTED** [review]
Hey @nakul-py! In order to display the error here, we'll need to update the sign in logic on the backend.

You can look at the Convex Auth docs for email validation for more info: https://labs.convex.dev/auth/config/passwords#email-address-validation

**Comment by kydecker** [comment]
Note you'll also need to add a changeset to this PR! You can do it from the command line with `pnpm changeset`.

File: .changeset/polite-monkeys-travel.md [hunk 3]
```diff
@@ -0,0 +1,5 @@
+---
+"namesake": minor
+---
+
+fix: Show error when signing in with unregistered email
```
Comment (kydecker) [inline .changeset/polite-monkeys-travel.md:5]: Thanks for adding a changeset!

File: src/routes/_unauthenticated/signin.tsx [hunk 4]
```diff
@@ -30,39 +30,82 @@ export const Route = createFileRoute("/_unauthenticated/signin")({
 });
 
 const SignIn = () => {
-  const { signIn } = useAuthActions();
+  const { signIn} = useAuthActions();
```
Comment (kydecker) [inline src/routes/_unauthenticated/signin.tsx]: Make sure that you run `pnpm check:fix` to fix formatting errors like the space missing here. If you have `formatOnSave` set to `true` in your editor it should make it easier :) — it should also run before you go to commit your changes.

File: src/routes/_unauthenticated/signin.tsx [hunk 5]
```diff
@@ -30,39 +30,82 @@ export const Route = createFileRoute("/_unauthenticated/signin")({
...
   const [flow, setFlow] = useState<Key>("signIn");
   const [email, setEmail] = useState<string>("");
   const [password, setPassword] = useState<string>("");
   const [isSubmitting, setIsSubmitting] = useState(false);
-  const [error, setError] = useState<string | null>(null);
+  const [error, setError] = useState<string | React.ReactNode | null>(null);
```
Comment (kydecker) [inline src/routes/_unauthenticated/signin.tsx]: Let's keep this as `string | null` for now.

File: src/routes/_unauthenticated/signin.tsx [hunk 6]
```diff
@@ -30,39 +30,82 @@ export const Route = createFileRoute("/_unauthenticated/signin")({
...
+  
+      return response.exists;
+    } catch (err) {
+      if (err instanceof ConvexError && err.message === 'User does not exist') {
+        return false; 
+      }
+      console.error(err);
+      return false;
+    }
+  };
```
Comment (kydecker) [inline src/routes/_unauthenticated/signin.tsx]: I see what you're trying to do here and it makes sense, but we actually want to test this on the backend in our `/convex` directory.

I did a little bit more research and discovered that Convex Auth doesn't easily surface error codes for use in production, so for this PR let's do a workaround which gets us most of the way there.

1. Eliminate this `checkUserExists` function.
2. Instead of what used to exist in our `catch()`, let's just display a generic message.

```diff
try {
  // Existing signIn function
} catch(error) {
- error instanceof ConvexError ? setError(error.message) : setError(error)
+ setError("Couldn't sign in. Check your information and try again.")
} finally {
  // Existing
}
```

That'll be enough to improve the user experience for now!

File: src/routes/_unauthenticated/signin.tsx (hunk 5 above)
Comment (nakul-py) [reply src/routes/_unauthenticated/signin.tsx]: Done

File: src/routes/_unauthenticated/signin.tsx (hunk 6 above)
Comment (nakul-py) [reply src/routes/_unauthenticated/signin.tsx]: done

File: src/routes/_unauthenticated/signin.tsx (hunk 4 above)
Comment (nakul-py) [reply src/routes/_unauthenticated/signin.tsx]: Ok, now i am sure about fixing formatting errors.

**Comment by nakul-py** [comment]
The output :-  

https://github.com/user-attachments/assets/0354c7b0-7a4e-47c6-a60a-b697a66a3e88

File: src/routes/_unauthenticated/signin.tsx [hunk 7]
```diff
@@ -44,25 +44,27 @@ const SignIn = () => {
...
+      await signIn("password", {
+        flow,
+        email,
+        password,
+        redirectTo: "/quests",
+      });
+      navigate({ to: "/" });
+    } catch (error) {
+      setError("Couldn't sign in. Check your information and try again.");
+      console.error(error);
```
Comment (kydecker) [inline src/routes/_unauthenticated/signin.tsx]: We can remove this `console.error`

**Review by kydecker — APPROVED** [review]
One tiny change, otherwise looks good! Thanks so much, @nakul-py!

File: src/routes/_unauthenticated/signin.tsx (hunk 7 above)
Comment (nakul-py) [reply src/routes/_unauthenticated/signin.tsx]: Done

Comment (nakul-py) [reply src/routes/_unauthenticated/signin.tsx]: Done

**Comment by nakul-py** [comment]
This commit will close this issue https://github.com/namesakefyi/namesake/pull/299/commits/fa90cdf0242bf2cfbaadc04602dbc3c534c7fc4b

**Comment by kydecker** [comment]
Thanks so much @nakul-py! 💟
